-- MySQL Script generated by MySQL Workbench
-- Wed Jan  3 17:07:35 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `User_ID` INT NULL DEFAULT NULL,
  `User_Name` VARCHAR(255) NULL DEFAULT NULL,
  `User_Role` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`User_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Survey`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Survey` (
  `Survey_ID` INT NOT NULL,
  `Survey_name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Survey_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Question` (
  `Question_ID` INT NOT NULL,
  `Survey_ID` INT NOT NULL,
  `Question` VARCHAR(45) NULL DEFAULT NULL,
  `Question_Type` VARCHAR(45) NULL DEFAULT NULL,
  `Question_Option` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Question_ID`, `Survey_ID`),
  INDEX `fk_Question_Survey1_idx` (`Survey_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Question_Survey1`
    FOREIGN KEY (`Survey_ID`)
    REFERENCES `mydb`.`Survey` (`Survey_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Answer` (
  `User_ID` INT NOT NULL,
  `Question_ID` INT NOT NULL,
  `Survey_ID` INT NOT NULL,
  `Answer_Choose` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`User_ID`, `Question_ID`, `Survey_ID`),
  INDEX `fk_User_has_Question_Question1_idx` (`Question_ID` ASC, `Survey_ID` ASC) VISIBLE,
  INDEX `fk_User_has_Question_User1_idx` (`User_ID` ASC) VISIBLE,
  CONSTRAINT `fk_User_has_Question_User1`
    FOREIGN KEY (`User_ID`)
    REFERENCES `mydb`.`User` (`User_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Question_Question1`
    FOREIGN KEY (`Question_ID` , `Survey_ID`)
    REFERENCES `mydb`.`Question` (`Question_ID` , `Survey_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
