-- MySQL Script generated by MySQL Workbench
-- Wed Jan  3 15:15:42 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `User_ID` INT NULL DEFAULT NULL,
  `User_Name` VARCHAR(255) NULL DEFAULT NULL,
  `User_Role` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`User_ID`));


-- -----------------------------------------------------
-- Table `mydb`.`Survey`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Survey` (
  `Survey_ID` INT NOT NULL,
  `Survey_name` VARCHAR(45) NULL,
  `Question_ID` VARCHAR(45) NULL,
  `Question_Type` VARCHAR(45) NULL,
  PRIMARY KEY (`Survey_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Answer` (
  `Survey_ID` INT NOT NULL,
  `User_ID` INT NOT NULL,
  `Answer_Choose` VARCHAR(45) NULL,
  PRIMARY KEY (`Survey_ID`, `User_ID`),
  INDEX `fk_Survey_has_User_User1_idx` (`User_ID` ASC) VISIBLE,
  INDEX `fk_Survey_has_User_Survey_idx` (`Survey_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Survey_has_User_Survey`
    FOREIGN KEY (`Survey_ID`)
    REFERENCES `mydb`.`Survey` (`Survey_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Survey_has_User_User1`
    FOREIGN KEY (`User_ID`)
    REFERENCES `mydb`.`User` (`User_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
